language: minimal

services:
  - docker

stages:
- name: Build and Push
- name: Deploy

jobs:
  include:
    - stage: Build and Push
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose push
        - docker logout

    - stage: Deploy
      before_script:
        - mkdir -p /home/travis/.ssh
        - openssl aes-256-cbc -K $encrypted_b94b5bb7b73b_key -iv $encrypted_b94b5bb7b73b_iv -in travis_key.enc -out /home/travis/.ssh/travis_key -d
      script:
        - chmod 600 /home/travis/.ssh/travis_key
        - scp -i /home/travis/.ssh/travis_key -o StrictHostKeyChecking=no ./docker-compose.yml "$GCP_USER"@"$GCP_VM_IP":/home/"$GCP_USER"/app/docker-compose.yml
        - ssh -i /home/travis/.ssh/travis_key "$GCP_USER"@"$GCP_VM_IP" "cd /home/$GCP_USER/app && PGUSER=\$PGUSER PGPASSWORD=\$PGPASSWORD PGDATABASE=\$PGDATABASE PGPORT=\$PGPORT PGHOST=\$PGHOST docker-compose pull && PGUSER=\$PGUSER PGPASSWORD=\$PGPASSWORD PGDATABASE=\$PGDATABASE PGPORT=\$PGPORT PGHOST=\$PGHOST docker-compose up -d"