language: minimal

services:
  - docker

stages:
  - name: Build and Push
  - name: Deploy

jobs:
  include:
    - stage: Build and Push
      script:
        - docker-compose -f docker-compose.yml build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose -f docker-compose.yml push

    - stage: Deploy
      script:
        # Déployez votre application ici (par exemple, en utilisant SSH pour copier docker-compose.yml et redéployer avec Docker Compose)
