language: minimal

services:
  - docker

stages:
# - name: Build and Push
- name: Deploy

jobs:
  include:
    # - stage: Build and Push
    #   script:
    #     - docker-compose build
    #     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #     - docker-compose push
    #     - docker logout

    - stage: Deploy
      script:
        - scp -i "$PRIVATE_SSH_KEY" -o StrictHostKeyChecking=no ./docker-compose.yml "$GCP_USER"@"$GCP_VM_IP":/home/"$GCP_USER"/app/docker-compose.yml
        - ssh -i "$PRIVATE_SSH_KEY" "$GCP_USER"@"$GCP_VM_IP" "cd /home/"$GCP_USER"/app && docker-compose pull && docker-compose up -d"
