language: minimal

services:
  - docker

stages:
- name: Build and Push
- name: Deploy

jobs:
  include:
    - stage: Build and Push
      script:
        - docker-compose build
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker-compose push
        - docker logout

    - stage: Deploy
      script:
        - ssh -i /chemin/vers/votre/cle/privee -o StrictHostKeyChecking=no utilisateur@adresse-ip-de-votre-vm << EOF
        cd /chemin/vers/votre/application
        docker-compose up -d
        exit
        EOF
