version: '3'

services:
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_DB: $PGDATABASE
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    container_name: api
    image: edgarcrssn/time-manager-api
    # build:
    #   context: .
    environment:
      ENV: $ENV
      PGUSER: $PGUSER
      PGPASSWORD: $PGPASSWORD
      PGDATABASE: $PGDATABASE
      PGPORT: $PGPORT
      PGHOST: $PGHOST
      VITE_API_URL: $VITE_API_URL
      VITE_FRONT_URL: $VITE_FRONT_URL
    ports:
      - '4000:4000'
    depends_on:
      - db

  ui:
    container_name: ui
    image: edgarcrssn/time-manager-ui
    # build:
    #   context: ./front
    environment:
      VITE_API_URL: $VITE_API_URL
    ports:
      - '5173:5173'
    depends_on:
      - api

volumes:
  dbdata: